name: MirrorBot Environment

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  GitHubMail: ${{ secrets.GHMAIL }}
  GitHubName: ${{ secrets.GHUSER }}

jobs:
  debug:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email cattobots@gmail.com
          git config --global user.name CattoBots
          git config --global credential.helper store
          echo "https://CattoBots:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Login to Docker Hub or Alternative
        run: |
          echo ${{ secrets.HUB_TOKEN }} | docker login ${{ secrets.DOCKER_HUB_URL }} -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Pull Docker Container
        run: |
          docker pull ${{ secrets.DOCKER_HUB_URL }}/${{ secrets.DOCKER_REPO }}

      - name: Run bot
        continue-on-error: true
        timeout-minutes: 340
        run: |
          docker run --privileged --rm -i ${{ secrets.DOCKER_HUB_URL }}/${{ secrets.DOCKER_REPO }}:latest

      - name: Loop Workflow
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > loop.txt
          git add loop.txt
          git commit -m "Workflow : Loop"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
